### ISSUE TITLE
Wrong result (sat instead of unsat)

### ISSUE THREAD

**Issue by dddejan** [xapantu/counting-smt#9]
There is no u's that satisfy the constraints, therefore #{u} can not be > 0.

``` smt2
(set-logic QF_LIA)

(assert (> (# u Int 
 (and 
   (<= 0 u) (<= u 10)
   (or (< u 0) (> u 10))
 ))
 0
))

(check-sat)
```

**Comment by xapantu** [comment]
Already fixed with the last commits.

**Comment by xapantu** [comment]
I have put more tests for > and < in examples/novars.smt.

**Comment by dddejan** [comment]
Oops, sorry. Forgot to recompile.
